# Generated by Django 3.1.12 on 2025-12-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='idea_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='idea_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
