# Generated by Django 3.1.12 on 2025-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20251215_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='teammate1_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='teammate2_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='teammate3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='teammate3_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='teammate4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='teammate4_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
